### ISSUE TITLE
Recommend CSV instead of JSON

### ISSUE THREAD

**Issue by ghost** [clips/clinspell#1]
The file stopwords_en.json is using the JSON format. However, it is a better idea to use the CSV format instead as every word is separated by a comma.

**Comment by PieterFivez** [comment]
Thanks for the suggestion, Mohamed. The commas are there because JSON dumped the list that way (and thus reads it in like that as well), so it really does not make a difference with the CSV format except for the straight brackets. If you have any other suggestions with respect to the code, please feel free to do a pull request.
