### ISSUE TITLE
Empty output from make_devcorpus.py

### ISSUE THREAD

**Issue by seden** [clips/clinspell#2]
Hi,

Thanks for making the source code available. I'm having some trouble when I run make_devcorpus.py. I'm able to run the preproc.py file on my text file, and when I run 
`python3 make_devcorpus.py ../merged_questions/preproc.txt en ../merged_questions/devcorpus.txt False 100000`

The devcorpus.txt output file just has this in it:
`[[], [], [], [], []]`

The devsample.json file that is created in the code directory has about 8MB worth of data. Is there something I'm doing wrong?

**Comment by PieterFivez** [comment]
Hi Seden,

It probably has something to do with the length of the lines in your file. There are ad hoc rules that make the function skip a line if:
 1) the line is too long (because our data had some very long lines we wanted to skip)
2) if no word in the vector vocabulary with sufficient window size (10) is found in the line

I have adapted the code to be more transparent about the second rule, and have removed the first rule. You can now explicitly state the minimal token window size for a development example (explained in the README). Please try again with this new script.

**Comment by seden** [comment]
Hi Pieter,
I think I've worked out the source of the issue. This is happening because none of the words in my text are showing up as part of the Fasttext vector vocab. The vector vocab is being loaded from the `embeddings_en.vec` file and each line of the file that I have contains both the word and the embedding. I don't know if something that's peculiar about the way my Fasttext is working, but the format seems correct to me. I have forked the project and I will be implementing a fix for it just to get it working with my text. Can you confirm if the vec file you get from Fasttext has only the words and not also the embeddings?

**Comment by PieterFivez** [comment]
The .vec file has on each line a word followed by its vector. I have now changed the code to not use the .vec file in any of the scripts, but always load embedding data from the .bin file using the fasttext library. Please check if the new version of the make_devcorpus.py script has mitigated your problem.

**Comment by seden** [comment]
Thanks for the update Pieter, I have forked the project and made a number of bugfixes and changes in the code already and I have it running to find the best parameters right now. You can see the commits I have made [here.](https://github.com/seden/clinspell) If you think these are any good, let me know and I will create a pull request. I think the version of the Fasttext library (latest from pypi 0.8.22) I'm using is different from yours so I had to make a few other changes in the ranking_experiments.py file as well.

**Comment by seden** [comment]
I will close this issue for now, since the source of the problem is solved.
