### ISSUE TITLE
Location of misspellings do not match

### ISSUE THREAD

**Issue by dalgu90** [clips/clinspell#5]
Hello, authors. Thank you for the great work!

I'm currently extracting typos in MIMIC-III using your code to test our work on typo correction, but I encountered a problem.
When extracting the typo (by running `python 2.7 extract_test.py NOTEEVENTS.csv`), the location of the typo words doesn't match.
(AssertionError in https://github.com/clips/clinspell/blob/master/code/extract_test.py#L65)
I think there's something I'm missing about the process, such as the version of MIMIC-III or python version.
(We ran it on python 2.7.17 (and also tried porting the code on python 3), using the `NOTEEVENTS.csv` file of MIMIC-III v1.4.)
Could you clarify more about the running environment?

Thanks
Juyong

**Comment by PieterFivez** [comment]
Dear Juyong,

The extraction script only works with the NOTEEVENTS.csv file from MIMIC-III v1.3 (since that was the version we were working with back then). We have now replicated the extraction using a virtual environment with Python 2.7. and the required dependencies in requirements.txt.

Kind regards,

Pieter
